
url: https://w0rldart.com
permalink: /:title
highlighter: rouge

title: 'Cloud and DevOps specialist'
description: 'Multi-cloud specialist: AWS, Google, Azure and Alibaba. Cloud development, Software Engineering and DevOps solutions.'

plugins:
    - jekyll-archives
    - jekyll-coffeescript
    - jekyll-redirect-from
    - jekyll-sitemap

whitelist:
  - jekyll-redirect-from

sass:
    style: compressed

jekyll-archives:
  enabled:
    - 'tags'
  layout: tag-posts
  permalinks:
    tag: '/tags/:name/'
